
DECLARE @LATITUDE     NUMERIC(20,16) = 37.5124831
	   ,@LONGITUDE    NUMERIC(20,16) = 127.0441089
	   ,@RADIUS       INT  = 1
	   ,@UTC_DATE     VARCHAR(8) = CONVERT(VARCHAR(8), GETUTCDATE(),112)
	   ,@UTC_TIME     VARCHAR(5) = CONVERT(VARCHAR(5), GETUTCDATE(),108)
	   ,@KEYWORD_NAME NVARCHAR(200) = N'병'
	   ,@AD_CODE INT = 12


SELECT A.AD_CODE
      ,A.TITLE, A.SUB_TITLE
	  ,A.LOGO_URL
      ,A.CLICK_CNT, A.GRADE_POINT
      ,A.COMPANY_CODE
      ,A.STORE_CODE
      ,A.MEMBER_CODE
	  ,A.FR_DATE, A.FR_TIME 
	  ,A.TO_DATE, A.TO_TIME
	  ,B.FR_UTC_DATE, B.TO_UTC_DATE
	  ,A.COMPANY_CODE
	  ,J.COMPANY_NAME AS COMPANY_NAME
	  ,A.MEMBER_CODE
	  ,ISNULL(I.USER_NAME,'') AS MEMBER_NAME
	 
	 
	 --,A.STORE_CODE
	  
	--,A.CONTENT
	--,B.FR_DATE, B.FR_TIME
	--,B.TO_DATE, B.TO_TIME
	--,B.AD_DEVICE_CODE
	--,C.DEVICE_CODE
	--,CONVERT(NUMERIC(18,2), ROUND(dbo.FN_TO_DISTANCE(@LATITUDE, @LONGITUDE, C.LATITUDE, C.LONGITUDE,'KM'),2)) RADIUS /*소숫점 둘째 자리에서 반올림*/
	--, H.KEYWORD_CODE, H.KEYWORD_NAME, CONVERT(DATETIME, B.FR_DATE + ' ' + B.FR_TIME) , dbo.FN_TO_DISTANCE(@LATITUDE, @LONGITUDE, C.LATITUDE, C.LONGITUDE,'KM'),CONVERT(DATETIME, B.TO_DATE + ' ' + CASE WHEN B.TO_TIME = '00:00' THEN '23:59:59' ELSE B.TO_TIME END),  c.*, G.*, E.*,  * 
 FROM T_AD A
INNER JOIN T_AD_DEVICE B
   ON A.AD_CODE = B.AD_CODE
INNER JOIN T_DEVICE C
   ON B.DEVICE_CODE = C.DEVICE_CODE
INNER JOIN T_SEARCH_KEYWORD E
   ON A.AD_CODE = E.AD_CODE
INNER JOIN T_CATEGORY_KEYWORD F
   ON E.CK_CODE = F.CK_CODE
INNER JOIN T_CATEGORY G
   ON F.CATEGORY_CODE = G.CATEGORY_CODE
INNER JOIN T_KEYWORD H
   ON H.KEYWORD_CODE = F.KEYWORD_CODE
 LEFT JOIN T_MEMBER I
   ON A.MEMBER_CODE = I.MEMBER_CODE
 LEFT JOIN T_COMPANY J
   ON J.COMPANY_CODE = A.COMPANY_CODE 

WHERE 1=1
  /*광고 코드 값이 있을 경우*/
  AND A.AD_CODE = @AD_CODE
  /*현재 타임 기준 광고시간 체크*/
  AND B.FR_UTC_DATE <= @UTC_DATE
  AND B.TO_UTC_DATE >= @UTC_DATE
  /*나라 마다 기준 시간이 다르기 때문에 서버 시간을 기준으로 등록한 광고 UTC시간을 더하여 24시간 기준 광고 시간을 표시한다.*/
  AND B.FR_TIME <= CONVERT(VARCHAR(5), DATEADD(HOUR, C.TIME_ZONE, CONVERT(VARCHAR(8), GETDATE(), 112) + ' ' + @UTC_TIME), 108)
  AND B.TO_TIME >= CONVERT(VARCHAR(5), DATEADD(HOUR, C.TIME_ZONE, CONVERT(VARCHAR(8), GETDATE(), 112) + ' ' + @UTC_TIME), 108)
  /*카테고리 선택이 값이 있을 경우 추가 CATEGORY_SEARCH_COND 클래스의 CATEGORY_CODE */
  AND ( SEARCH_CATEGORY_CODE LIKE '00270%'
        OR SEARCH_CATEGORY_CODE LIKE '00171%')  
  AND dbo.FN_TO_DISTANCE(@LATITUDE, @LONGITUDE, C.LATITUDE, C.LONGITUDE,'KM') <= @RADIUS
  /*키워드명이 있을 경우 조회 조건 추가*/
  AND F.KEYWORD_NAME LIKE N'%' + @KEYWORD_NAME + '%'
  /*CATEGORY_SEARCH_COND 클래스의 SEARCH_KEYWORD_CODE에 값이 있을 경우 조회 갯수 만큼 IN 조건 추가*/
  AND F.KEYWORD_CODE IN (4883, 4884)
ORDER BY A.AD_CODE DESC -- CASE WHEN ISNULL(A.STORE_CODE,'') <> '' THEN 1 ELSE 0 END DESC, dbo.FN_TO_DISTANCE(@LATITUDE, @LONGITUDE, C.LATITUDE, C.LONGITUDE,'KM')

