DECLARE @STORE_CODE INT = 1

      , @MAX_LEVEL INT, @MIN_LEVEL INT = 2
      , @SQL_DESC NVARCHAR(MAX),          @SQL_ORDER_SQL NVARCHAR(MAX)
      , @SQL_ORDER_FIX_SQL NVARCHAR(MAX), @END_SQL_DESC  NVARCHAR(MAX)


SELECT @MAX_LEVEL = MAX(LEVEL) FROM T_STORE_WEBMENU
SET @MAX_LEVEL = 4

SET @SQL_DESC =  'SELECT  * FROM ( ' + CHAR(13)
SET @SQL_DESC = @SQL_DESC + 'SELECT RIGHT(''0000'' + CONVERT(VARCHAR(4), SEQ),4) AS ORDER_SEQ, * FROM T_STORE_WEBMENU  ' + CHAR(13)
SET @SQL_DESC = @SQL_DESC + 'WHERE LEVEL= 1  ' + CHAR(13)


	SET @SQL_ORDER_SQL = ''
	SET @SQL_ORDER_FIX_SQL  = '[REPLACE]'
WHILE @MIN_LEVEL <= @MAX_LEVEL
BEGIN

	SET @SQL_ORDER_SQL = ''
	SET @SQL_ORDER_FIX_SQL = REPLACE(@SQL_ORDER_FIX_SQL,  '[REPLACE]', '+   (SELECT [REPLACE] + ISNULL(RIGHT(''0000'' + CONVERT(VARCHAR(4), MAX(P_' +  CONVERT(VARCHAR(10), @MIN_LEVEL) + '.SEQ)),4),'''') FROM T_STORE_WEBMENU P_' +  CONVERT(VARCHAR(10), @MIN_LEVEL) + ' ' + CHAR(13)
                                                           + '          WHERE MAX(P_' + CONVERT(VARCHAR(10), @MIN_LEVEL -1) + '.STORE_CODE) = P_' +  CONVERT(VARCHAR(10), @MIN_LEVEL) + '.STORE_CODE AND MAX(P_' +  CONVERT(VARCHAR(10), @MIN_LEVEL -1) + '.PARENT_CODE) = P_' +  CONVERT(VARCHAR(10), @MIN_LEVEL) + '.CODE ' + CHAR(13)
														   
	                                                    +' )')
	SET @SQL_ORDER_SQL = @SQL_ORDER_SQL + 'SELECT (SELECT [REPLACE] +  RIGHT(''0000'' + CONVERT(VARCHAR(4), ISNULL(MAX(P_1.SEQ),'''')),4) FROM T_STORE_WEBMENU P_1 ' + CHAR(13)
	SET @SQL_ORDER_SQL = @SQL_ORDER_SQL + '          WHERE P_0.STORE_CODE = P_1.STORE_CODE AND P_0.PARENT_CODE = P_1.CODE)  +  RIGHT(''0000'' + CONVERT(VARCHAR(4),P_0.SEQ),4) ' + CHAR(13)


	SET @SQL_ORDER_SQL = @SQL_ORDER_SQL + ' AS ORDER_SEQ ' + CHAR(13)
	SET @SQL_ORDER_SQL = @SQL_ORDER_SQL + ', * FROM T_STORE_WEBMENU P_0 ' + CHAR(13)
	SET @SQL_ORDER_SQL = @SQL_ORDER_SQL + 'WHERE LEVEL= ' + CONVERT(VARCHAR(20), @MIN_LEVEL)  + CHAR(13)



	SET @SQL_ORDER_SQL = REPLACE(@SQL_ORDER_SQL, '[REPLACE]',  @SQL_ORDER_FIX_SQL)
	SET @SQL_DESC = @SQL_DESC + 'UNION ALL  ' +  @SQL_ORDER_SQL


	SET @MIN_LEVEL = @MIN_LEVEL + 1
END
SET @END_SQL_DESC = ') A ORDER BY ORDER_SEQ' + CHAR(13)
SET @SQL_DESC = @SQL_DESC+ @END_SQL_DESC
SET @SQL_DESC = REPLACE(@SQL_DESC,'[REPLACE] +' ,'')
SET @SQL_DESC = REPLACE(@SQL_DESC,'[REPLACE]' ,'')
SET @SQL_DESC = REPLACE(@SQL_DESC,'SELECT +' ,'SELECT ')

EXEC (@SQL_DESC)