
DECLARE @KEYWORD_NAME NVARCHAR(200) = N'경기'
       ,@CATEGORY_TYPE INT = 2
	   ,@CATEGORY_TYPE2 INT = 2
	   ,@KEYWORD_TYPE INT = 1
	   ,@TYPE INT =0 ;

DECLARE @TABLE TABLE
(
	SEQ FLOAT PRIMARY KEY
  --, CATEGORY_CODE INT
  --, PARENT_CATEGORY_CODE INT
  , SEARCH_CATEGORY_CODE VARCHAR(100)
  , NAME VARCHAR(500)
)

INSERT INTO @TABLE
SELECT CONVERT(FLOAT, POWER(10,5)) * CONVERT(FLOAT, POWER(10,5)) * CONVERT(FLOAT, A.ORDER_SEQ)   AS SEQ
   --, A.CATEGORY_CODE, A.PARENT_CATEGORY_CODE
     , A.SEARCH_CATEGORY_CODE, A.CATEGORY_NAME AS NAME
 FROM T_CATEGORY A
 INNER JOIN T_CATEGORY_KEYWORD AB
   ON A.CATEGORY_CODE = AB.CATEGORY_CODE
INNER JOIN T_KEYWORD AC
   ON AC.KEYWORD_CODE = AB.KEYWORD_CODE
  AND AC.KEYWORD_TYPE = @KEYWORD_TYPE
  AND AC.IS_SYNONYM = 0
WHERE A.CATEGORY_TYPE = @CATEGORY_TYPE 
  AND A.CATEGORY_TYPE2= @CATEGORY_TYPE2
  AND A.LEVEL_DEPTH = 1
 AND ((AC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
	                           WHERE KEYWORD_NAME LIKE N'%경기%' OR KEYWORD_UNITS LIKE N'%ㄱㅕㅇㄱㅣ%' 
							      OR (1=1 AND CHOSUNG LIKE '%ㄱㄱ%' 
								      AND JUNGSUNG LIKE '%ㅕl%' 
									  AND JONGSUNG LIKE '%ㅇ%'
									  )
								)
							 )
		AND (AC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
	                            WHERE KEYWORD_NAME LIKE N'%안성%' OR KEYWORD_UNITS LIKE N'%ㅇㅏㄴㅅㅓㅇ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㅇㅅ%' 
								      AND JUNGSUNG LIKE '%ㅏㅓ%' 
									  AND JONGSUNG LIKE '%ㄴㅇ%'
									  )
								)
							 )
		AND (AC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
	                            WHERE KEYWORD_NAME LIKE N'%금석%' OR KEYWORD_UNITS LIKE N'%ㄱㅡㅁㅅㅓㄱ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㄱㅅ%' 
								      AND JUNGSUNG LIKE '%ㅡㅓ%' 
									  AND JONGSUNG LIKE '%ㅁㄱ%'
									  )
								)
							)
			)
IF @@ROWCOUNT > 0
BEGIN 
   SET @TYPE = 1
END


	INSERT INTO @TABLE
	SELECT  CONVERT(FLOAT, POWER(10,5)) * CONVERT(FLOAT, POWER(10,5)) * CONVERT(FLOAT, B.ORDER_SEQ) + CONVERT(FLOAT, A.ORDER_SEQ) * CONVERT(FLOAT, POWER(10,5))   AS SEQ 
		 --, A.CATEGORY_CODE, A.PARENT_CATEGORY_CODE
		 , A.SEARCH_CATEGORY_CODE, B.CATEGORY_NAME + ' ' + A.CATEGORY_NAME AS NAME
	 FROM T_CATEGORY A
	 INNER JOIN T_CATEGORY_KEYWORD AB
	   ON A.CATEGORY_CODE = AB.CATEGORY_CODE
	INNER JOIN T_KEYWORD AC
	   ON AC.KEYWORD_CODE = AB.KEYWORD_CODE
	  AND AC.KEYWORD_TYPE = @KEYWORD_TYPE
	  AND AC.IS_SYNONYM = 0
	INNER JOIN T_CATEGORY B
	   ON B.CATEGORY_CODE = A.PARENT_CATEGORY_CODE
	INNER JOIN T_CATEGORY_KEYWORD BB
	   ON B.CATEGORY_CODE = BB.CATEGORY_CODE
	INNER JOIN T_KEYWORD BC 
	   ON BC.KEYWORD_CODE = BB.KEYWORD_CODE
	  AND BC.KEYWORD_TYPE = @KEYWORD_TYPE
	  AND BC.IS_SYNONYM = 0
	WHERE A.CATEGORY_TYPE = @CATEGORY_TYPE 
	  AND A.CATEGORY_TYPE2= @CATEGORY_TYPE2
	  AND A.LEVEL_DEPTH = 2
       AND ((AC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
	                           WHERE KEYWORD_NAME LIKE N'%경기%' OR KEYWORD_UNITS LIKE N'%ㄱㅕㅇㄱㅣ%' 
							      OR (1=1 AND CHOSUNG LIKE '%ㄱㄱ%' 
								      AND JUNGSUNG LIKE '%ㅕl%' 
									  AND JONGSUNG LIKE '%ㅇ%'
									  )
							 
							 )
			OR BC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
			                      WHERE KEYWORD_NAME LIKE N'%경기%' OR KEYWORD_UNITS LIKE N'%ㄱㅕㅇㄱㅣ%' 
							      OR (1=1 AND CHOSUNG LIKE '%ㄱㄱ%' 
								      AND JUNGSUNG LIKE '%ㅕl%' 
									  AND JONGSUNG LIKE '%ㅇ%'
									  )
								   )
		    )
			AND
			((AC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
	                            WHERE KEYWORD_NAME LIKE N'%안성%' OR KEYWORD_UNITS LIKE N'%ㅇㅏㄴㅅㅓㅇ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㅇㅅ%' 
								      AND JUNGSUNG LIKE '%ㅏㅓ%' 
									  AND JONGSUNG LIKE '%ㄴㅇ%'
									  )
									  )
							 
							 )
			OR BC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
			                      WHERE KEYWORD_NAME LIKE N'%안성%' OR KEYWORD_UNITS LIKE N'%ㅇㅏㄴㅅㅓㅇ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㅇㅅ%' 
								      AND JUNGSUNG LIKE '%ㅏㅓ%' 
									  AND JONGSUNG LIKE '%ㄴㅇ%'
									  )
								   )
			)
			AND
			((AC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
	                             WHERE KEYWORD_NAME LIKE N'%금석%' OR KEYWORD_UNITS LIKE N'%ㄱㅡㅁㅅㅓㄱ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㄱㅅ%' 
								      AND JUNGSUNG LIKE '%ㅡㅓ%' 
									  AND JONGSUNG LIKE '%ㅁㄱ%'
									  )
							    )
							 )
			OR BC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
			                       WHERE KEYWORD_NAME LIKE N'%금석%' OR KEYWORD_UNITS LIKE N'%ㄱㅡㅁㅅㅓㄱ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㄱㅅ%' 
								      AND JUNGSUNG LIKE '%ㅡㅓ%' 
									  AND JONGSUNG LIKE '%ㅁㄱ%'
									  )
								   )
			)
		)

	IF @@ROWCOUNT > 0
	BEGIN 
	   SET @TYPE = @TYPE + 1
	END


IF @TYPE <= 1
BEGIN
   INSERT INTO @TABLE
	SELECT CONVERT(FLOAT, POWER(10,5)) * CONVERT(FLOAT, POWER(10,5)) * CONVERT(FLOAT, C.ORDER_SEQ) + CONVERT(FLOAT, B.ORDER_SEQ) * CONVERT(FLOAT, POWER(10,5)) + CONVERT(FLOAT, A.ORDER_SEQ) * 1    AS SEQ 
	--,  A.CATEGORY_CODE, A.PARENT_CATEGORY_CODE
	, A.SEARCH_CATEGORY_CODE, C.CATEGORY_NAME + ' ' + B.CATEGORY_NAME + ' ' + A.CATEGORY_NAME AS NAME
	 FROM T_CATEGORY A
	 INNER JOIN T_CATEGORY_KEYWORD AB
	   ON A.CATEGORY_CODE = AB.CATEGORY_CODE
	INNER JOIN T_KEYWORD AC
	   ON AC.KEYWORD_CODE = AB.KEYWORD_CODE
	  AND AC.KEYWORD_TYPE = @KEYWORD_TYPE
	  AND AC.IS_SYNONYM = 0
	INNER JOIN T_CATEGORY B
	   ON B.CATEGORY_CODE = A.PARENT_CATEGORY_CODE
	INNER JOIN T_CATEGORY_KEYWORD BB
	   ON B.CATEGORY_CODE = BB.CATEGORY_CODE
	INNER JOIN T_KEYWORD BC 
	   ON BC.KEYWORD_CODE = BB.KEYWORD_CODE
	  AND BC.KEYWORD_TYPE = @KEYWORD_TYPE
	  AND BC.IS_SYNONYM = 0
	INNER JOIN T_CATEGORY C
	   ON C.CATEGORY_CODE = B.PARENT_CATEGORY_CODE
	INNER JOIN T_CATEGORY_KEYWORD CB
	   ON C.CATEGORY_CODE = CB.CATEGORY_CODE
	INNER JOIN T_KEYWORD CC 
	   ON CC.KEYWORD_CODE = CB.KEYWORD_CODE
	  AND CC.KEYWORD_TYPE = @KEYWORD_TYPE
	  AND CC.IS_SYNONYM = 0
	WHERE A.CATEGORY_TYPE = @CATEGORY_TYPE 
	  AND A.CATEGORY_TYPE2= @CATEGORY_TYPE2
	  AND A.LEVEL_DEPTH = 3
	  /*압에서 부터 2개*/
	   AND ((AC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
	                           WHERE KEYWORD_NAME LIKE N'%경기%' OR KEYWORD_UNITS LIKE N'%ㄱㅕㅇㄱㅣ%' 
							      OR (1=1 AND CHOSUNG LIKE '%ㄱㄱ%' 
								      AND JUNGSUNG LIKE '%ㅕl%' 
									  AND JONGSUNG LIKE '%ㅇ%'
									  )
							 
							 )
			OR BC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
			                      WHERE KEYWORD_NAME LIKE N'%경기%' OR KEYWORD_UNITS LIKE N'%ㄱㅕㅇㄱㅣ%' 
							      OR (1=1 AND CHOSUNG LIKE '%ㄱㄱ%' 
								      AND JUNGSUNG LIKE '%ㅕl%' 
									  AND JONGSUNG LIKE '%ㅇ%'
									  )
								   )
			OR CC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
			                    WHERE KEYWORD_NAME LIKE N'%경기%' OR KEYWORD_UNITS LIKE N'%ㄱㅕㅇㄱㅣ%' 
							      OR (1=1 AND CHOSUNG LIKE '%ㄱㄱ%' 
								      AND JUNGSUNG LIKE '%ㅕl%' 
									  AND JONGSUNG LIKE '%ㅇ%'
									  )
								   )
		    )
			AND
			((AC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
	                            WHERE KEYWORD_NAME LIKE N'%안성%' OR KEYWORD_UNITS LIKE N'%ㅇㅏㄴㅅㅓㅇ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㅇㅅ%' 
								      AND JUNGSUNG LIKE '%ㅏㅓ%' 
									  AND JONGSUNG LIKE '%ㄴㅇ%'
									  )
									  )
							 
							 )
			OR BC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
			                      WHERE KEYWORD_NAME LIKE N'%안성%' OR KEYWORD_UNITS LIKE N'%ㅇㅏㄴㅅㅓㅇ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㅇㅅ%' 
								      AND JUNGSUNG LIKE '%ㅏㅓ%' 
									  AND JONGSUNG LIKE '%ㄴㅇ%'
									  )
								   )
			OR CC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
			                      WHERE KEYWORD_NAME LIKE N'%안성%' OR KEYWORD_UNITS LIKE N'%ㅇㅏㄴㅅㅓㅇ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㅇㅅ%' 
								      AND JUNGSUNG LIKE '%ㅏㅓ%' 
									  AND JONGSUNG LIKE '%ㄴㅇ%'
									  )
								   )
			)
			AND
			((AC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
	                            WHERE KEYWORD_NAME LIKE N'%금석%' OR KEYWORD_UNITS LIKE N'%ㄱㅡㅁㅅㅓㄱ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㄱㅅ%' 
								      AND JUNGSUNG LIKE '%ㅡㅓ%' 
									  AND JONGSUNG LIKE '%ㅁㄱ%'
									  )
									  )
							 
							 )
			OR BC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
			                       WHERE KEYWORD_NAME LIKE N'%금석%' OR KEYWORD_UNITS LIKE N'%ㄱㅡㅁㅅㅓㄱ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㄱㅅ%' 
								      AND JUNGSUNG LIKE '%ㅡㅓ%' 
									  AND JONGSUNG LIKE '%ㅁㄱ%'
									  )
								   )
			OR CC.BASE_CODE IN (SELECT BASE_CODE FROM T_KEYWORD 
			                       WHERE KEYWORD_NAME LIKE N'%금석%' OR KEYWORD_UNITS LIKE N'%ㄱㅡㅁㅅㅓㄱ%'
								     OR (1=1 AND CHOSUNG LIKE '%ㄱㅅ%' 
								      AND JUNGSUNG LIKE '%ㅡㅓ%' 
									  AND JONGSUNG LIKE '%ㅁㄱ%'
									  )
								   )
			)
	)
		

							 
END

SELECT SEARCH_CATEGORY_CODE AS CODE, NAME
  FROM @TABLE
ORDER BY SEQ

  

